### PR TITLE
fix(serialport): data race on the  `isClosing` bool status of the serial port

### LINKED ISSUE #1006: Data Race on Close command
### Describe the problem

A data race is detected 
```
2025/01/10 14:53:20 stderr: ==================
2025/01/10 14:53:20 stderr: WARNING: DATA RACE
2025/01/10 14:53:20 stderr: Read at 0x00c000447988 by goroutine 80:
2025/01/10 14:53:20 stderr:   main.(*serport).reader()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/serialport.go:88 +0x167
2025/01/10 14:53:20 stderr:   main.spHandlerOpen()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/serialport.go:345 +0x1467
2025/01/10 14:53:20 stderr:   main.checkCmd.gowrap4()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:157 +0x6b
2025/01/10 14:53:20 stderr: 
2025/01/10 14:53:20 stderr: Previous write at 0x00c000447988 by goroutine 86:
2025/01/10 14:53:20 stderr:   main.(*serport).Close()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/serialport.go:351 +0x37
2025/01/10 14:53:20 stderr:   main.spClose()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/serial.go:267 +0xee
2025/01/10 14:53:20 stderr:   main.checkCmd.gowrap5()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:163 +0x44
2025/01/10 14:53:20 stderr: 
2025/01/10 14:53:20 stderr: Goroutine 80 (running) created at:
2025/01/10 14:53:20 stderr:   main.checkCmd()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:157 +0x366
2025/01/10 14:53:20 stderr:   main.(*hub).run()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:111 +0x244
2025/01/10 14:53:20 stderr:   main.loop.gowrap2()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/main.go:412 +0x33
2025/01/10 14:53:20 stderr: 
2025/01/10 14:53:20 stderr: Goroutine 86 (running) created at:
2025/01/10 14:53:20 stderr:   main.checkCmd()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:163 +0x584
2025/01/10 14:53:20 stderr:   main.(*hub).run()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:111 +0x244
2025/01/10 14:53:20 stderr:   main.loop.gowrap2()
2025/01/10 14:53:20 stderr:       /home/dido/code/arduino/arduino-create-agent/main.go:412 +0x33
2025/01/10 14:53:20 stderr: ==================
```

### To reproduce

- launch the service `task run`
- open the `http://127.0.0.1:8991/` console
- attach a board via USB
- type the command `open /dev/ttyACM0 115200`
- type the command `close /dev/ttyACM0`
- the console where the service is running shows the data-race warning.

### Expected behavior

do not have the race condition

### Arduino Create Agent version

1,6,1

### Operating system

Linux

### Operating system version

20.04

### Browser

Chroome

### Browser version

Chroome

### Additional context

_No response_

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-create-agent/issues?q=)
- [x] I verified the problem still occurs when using the latest version
- [x] My report contains all necessary details

### PR DESCRIPTION
**Pull request by dido18**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?**
Fix a DATA RACE on the `isClosing` variable of the seiral port.

- **What is the current behavior?**
There are two routines that read and write the `isClosing` variable concurrently. 
    - the routine of the `open` command reads the `isClosing` variable to verify if it must stop reading from the serial port
    - the routine of the `close` command writes the `isClosing` (setting to true)  variable to inform that the serial port must be closed.
  
Steps to reproduce
 - connect a board to the PC
 -  launch the cloud-agent locally with `task run ` 
 -  visit the debug console `http://127.0.0.1:8991/`
 -  type `open /dev/ttyACM0 115200`
 -  type `close /dev/ttyACM0`
 - the DATA RACE warning appears in the console where the cloud-agent is running: 
 ```
 2025/01/20 10:12:07 stderr: ==================
2025/01/20 10:12:07 stderr: WARNING: DATA RACE
2025/01/20 10:12:07 stderr: Read at 0x00c0002b8b18 by goroutine 61:
2025/01/20 10:12:07 stderr:   main.(*serport).reader()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/serialport.go:88 +0x167
2025/01/20 10:12:07 stderr:   main.spHandlerOpen()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/serialport.go:345 +0x1467
2025/01/20 10:12:07 stderr:   main.checkCmd.gowrap4()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:157 +0x6b
2025/01/20 10:12:07 stderr: 
2025/01/20 10:12:07 stderr: Previous write at 0x00c0002b8b18 by goroutine 66:
2025/01/20 10:12:07 stderr:   main.(*serport).Close()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/serialport.go:351 +0x37
2025/01/20 10:12:07 stderr:   main.spClose()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/serial.go:267 +0xee
2025/01/20 10:12:07 stderr:   main.checkCmd.gowrap5()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:163 +0x44
2025/01/20 10:12:07 stderr: 
2025/01/20 10:12:07 stderr: Goroutine 61 (running) created at:
2025/01/20 10:12:07 stderr:   main.checkCmd()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:157 +0x366
2025/01/20 10:12:07 stderr:   main.(*hub).run()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:111 +0x244
2025/01/20 10:12:07 stderr:   main.loop.gowrap2()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/main.go:412 +0x33
2025/01/20 10:12:07 stderr: 
2025/01/20 10:12:07 stderr: Goroutine 66 (running) created at:
2025/01/20 10:12:07 stderr:   main.checkCmd()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:163 +0x584
2025/01/20 10:12:07 stderr:   main.(*hub).run()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/hub.go:111 +0x244
2025/01/20 10:12:07 stderr:   main.loop.gowrap2()
2025/01/20 10:12:07 stderr:       /home/dido/code/arduino/arduino-create-agent/main.go:412 +0x33
2025/01/20 10:12:07 stderr: ==================
```

* **What is the new behavior?**
Add an atomic.Bool to control the access of the `isClosing` status of the serial port.

- **Does this PR introduce a breaking change?**

* **Other information**:

### CODE REVIEW

File: serialport.go [hunk 1]
```diff
@@ -84,13 +87,15 @@ func (p *serport) reader(buftype string) {
...
 
+		p.mu.Lock()
 		//if we detect that port is closing, break out of this for{} loop.
 		if p.isClosing {
 			strmsg := "Shutting down reader on " + p.portConf.Name
 			log.Println(strmsg)
 			h.broadcastSys <- []byte(strmsg)
 			break
 		}
+		p.mu.Unlock()
```
Comment (cmaglie) [inline serialport.go:98]: If the `break` path is taken doesn't the mutex remain locked?

**Review by cmaglie — CHANGES_REQUESTED** [review]
If we only need to synchronize access to a single variable maybe an `atomic.Bool` could be better?

**Review by cmaglie — APPROVED** [review]

**Review by lucarin91 — APPROVED** [review]

**Review by cmaglie — APPROVED** [review]
Retested on Linux, and now seems working OK! ✅
