### PR TITLE
Check the folder content in new version of the agent on macos

### LINKED ISSUE #795: "Old agent installation" error is not always triggered when expected
### Describe the problem

The new DMG file in [ArduinoCreateAgent-1.3.1-osx-amd64-installer.dmg](https://github.com/arduino/arduino-create-agent/releases/download/1.3.1/ArduinoCreateAgent-1.3.1-osx-amd64-installer.dmg) is a great improvement from the old installer. But since the new installation path (`/Application/ArduinoCreateAgent.app`) is different from the older one (`/Users/sebastianwikstrom/Applications/ArduinoCreateAgent`), this is will not result in the old application being overwritten. Instead, the user has to manually remove the old application.

In some cases, the presense of an older Create Agent version can trigger this error:

error

## Problem 1: Assuming the default installation path

It seems like the trigger for the error is the presence of an `~/Applications/ArduinoCreateAgent` folder.

An older version of the Create Agent can be present **and running** from a different location, without triggering the error. This results in two instances of the application running:

Screenshot 2023-06-01 at 15 35 18

On the other hand, the error is produced even if the `~/Applications/ArduinoCreateAgent` folder is empty. This seems unnecessary.

## Problem 2: Does not trigger if Create Agent is opened via Spotlight when a different version is running

Opening the application via Spotlight does not display the error or launch the application.

Screenshot 2023-06-01 at 14 41 17

### To reproduce

Running two instances at the same time:

1. Install or move ArduinoCreateAgent.app (1.2.7) to a path that is not `~/Applications/ArduinoCreateAgent`
2. Run ArduinoCreateAgent.app (1.2.7) so it appears in the menu bar
3. If the `~/Applications/ArduinoCreateAgent` folder exists, remove it.
4. Run the new ArduinoCreateAgent.app (1.3.1)

🐛 Another instance of the application starts, with two Create Agent icons now appearing in the menu bar

Spotlight issue:

1. Have both 1.2.7 and 1.3.1 installed.
2. Run 1.2.7
3. Press <kbd>Command</kbd> + <kbd>Space</kbd> to open Spotlight
4. Search for 'ArduinoCreateAgent'
5. Open the newer version (in Applications by default)

🐛 Nothing happens

### Expected behavior

* I think the application shouldn't care about the presence of any particular file or folder. I would only expect to get an error if another Create Agent process is currently running.
* Opening the application via Spotlight should not prevent the error from being displayed.

### Arduino Create Agent version

1.3.1

### Operating system

macOS

### Operating system version

13.2.1 (22D68)

### Browser

Chrome

### Browser version

Version 113.0.5672.126 (Official Build) (arm64)

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-create-agent/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by umbynos**
**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?**

bug fix

- **What is the current behavior?**

when uninstalling an old version of the agent (e.g. 1.2.7) a folder in `~/Applications/ArduinoCreateAgent` could be left behind (empty, but existing), after uninstalling.
This will trigger this error when running a new agent:

image

* **What is the new behavior?**

The check in the new agent is performed on the existence of the `ArduinoCreateAgent.app` subfolder.

- **Does this PR introduce a breaking change?**

no
* **Other information**:

Partially fixes #795

### CODE REVIEW

**Comment by umbynos** [comment]
test release [here](https://github.com/arduino/arduino-create-agent/releases/tag/1.3.2)

File: main.go [hunk 1]
```diff
@@ -453,7 +453,8 @@ func oldInstallExists() bool {
 	if binIsOld {
 		return false
 	}
-	return oldAgentPath.Exist()
+	oldFiles, _ := oldAgentPath.ReadDir()
+	return oldFiles.Len() != 0
```
Comment (cmaglie) [inline main.go:457]: I'd check for the existence of the directory: `~/Applications/ArduinoCreateAgent/ArduinoCreateAgent.app`

**Review by cmaglie — CHANGES_REQUESTED** [review]

**Review by cmaglie — APPROVED** [review]
